rolling deployment in partition-style
Signed-off-by: mingzhou.swx <mingzhou.swx@alibaba-inc.com>

diff --git a/.github/workflows/e2e-advanced-deployment-1.19.yaml b/.github/workflows/e2e-advanced-deployment-1.19.yaml
--- a/.github/workflows/e2e-advanced-deployment-1.19.yaml
+++ b/.github/workflows/e2e-advanced-deployment-1.19.yaml
@@ -90,12 +90,30 @@ jobs:
             echo "Timeout to wait for kruise-rollout ready"
             exit 1
           fi
-      - name: Run E2E Tests
+      - name: Run E2E Tests For Deployment Controller
         run: |
           export KUBECONFIG=/home/runner/.kube/config
           make ginkgo
           set +e
           ./bin/ginkgo -timeout 60m -v --focus='Advanced Deployment' test/e2e
+          retVal=$?
+          # kubectl get pod -n kruise-rollout --no-headers | grep manager | awk '{print $1}' | xargs kubectl logs -n kruise-rollout
+          restartCount=$(kubectl get pod -n kruise-rollout --no-headers | awk '{print $4}')
+          if [ "${restartCount}" -eq "0" ];then
+              echo "Kruise-rollout has not restarted"
+          else
+              kubectl get pod -n kruise-rollout --no-headers
+              echo "Kruise-rollout has restarted, abort!!!"
+              kubectl get pod -n kruise-rollout --no-headers| awk '{print $1}' | xargs kubectl logs -p -n kruise-rollout
+              exit 1
+          fi
+          exit $retVal
+      - name: Run E2E Tests For Control Plane
+        run: |
+          export KUBECONFIG=/home/runner/.kube/config
+          make ginkgo
+          set +e
+          ./bin/ginkgo -timeout 60m -v --focus='Advanced Deployment canary rollout with Ingress' test/e2e
           retVal=$?
           # kubectl get pod -n kruise-rollout --no-headers | grep manager | awk '{print $1}' | xargs kubectl logs -n kruise-rollout
           restartCount=$(kubectl get pod -n kruise-rollout --no-headers | awk '{print $4}')
